import '../decoders.dart';
import 'obd_command.dart';

class Commands {
  static final Map<String, ObdCommand> allCommands = {
    "ATD": ObdCommand(CommandProperties("ATD", "Set to default", 5, null, live: false, maxValue: 100, minValue: 0)),
    "ATZ": ObdCommand(CommandProperties("ATZ", "Reset", 5, null, live: false, maxValue: 100, minValue: 0)),
    "ATRV": ObdCommand(CommandProperties("ATRV", "Voltage", 5, null, live: false, maxValue: 100, minValue: 0)),
    "ATL0": ObdCommand(CommandProperties("ATL0", "Linefeeds Off", 5, null, live: false, maxValue: 100, minValue: 0)),
    "ATE0": ObdCommand(CommandProperties("ATE0", "Echo Off", 5, null, live: false, maxValue: 100, minValue: 0)),
    "ATH1": ObdCommand(CommandProperties("ATH1", "Headers On", 5, null, live: false, maxValue: 100, minValue: 0)),
    "ATH0": ObdCommand(CommandProperties("ATH0", "Headers Off", 5, null, live: false, maxValue: 100, minValue: 0)),
    "ATAT1": ObdCommand(CommandProperties("ATAT1", "Adaptive Timing On", 5, null, live: false, maxValue: 100, minValue: 0)),
    "ATSTFF": ObdCommand(CommandProperties("ATSTFF", "Set Time to Fast", 5, null, live: false, maxValue: 100, minValue: 0)),
    "ATDPN": ObdCommand(CommandProperties("ATDPN", "Describe Protocol Number", 5, null, live: false, maxValue: 100, minValue: 0)),
    "0100": ObdCommand(CommandProperties("0100", "Supported PIDs [01-20]", 5, null, live: false, maxValue: 100, minValue: 0)),
    "0101": ObdCommand(CommandProperties("0101", "Status since DTCs cleared", 5, StatusDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0102": ObdCommand(CommandProperties("0102", "DTC that triggered the freeze frame", 5, SingleDtcDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0103": ObdCommand(CommandProperties("0103", "Fuel System Status", 3, FuelStatusDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0104": ObdCommand(CommandProperties("0104", "Calculated Engine Load", 2, PercentDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0105": ObdCommand(CommandProperties("0105", "Coolant temperature", 2, TemperatureDecoder(), live: true, maxValue: 215, minValue: -40)),
    "0106": ObdCommand(CommandProperties("0106", "Short Term Fuel Trim - Bank 1", 2, PercentCenteredDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0107": ObdCommand(CommandProperties("0107", "Long Term Fuel Trim - Bank 1", 2, PercentCenteredDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0108": ObdCommand(CommandProperties("0108", "Short Term Fuel Trim - Bank 2", 2, PercentCenteredDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0109": ObdCommand(CommandProperties("0109", "Long Term Fuel Trim - Bank 2", 2, PercentCenteredDecoder(), live: true, maxValue: 100, minValue: 0)),
    "010A": ObdCommand(CommandProperties("010A", "Fuel Pressure", 2, FuelPressureDecoder(), live: true, maxValue: 765, minValue: 0)),
    "010B": ObdCommand(CommandProperties("010B", "Intake Manifold Pressure", 2, PressureDecoder(), live: true, maxValue: 255, minValue: 0)),
    "010C": ObdCommand(CommandProperties("010C", "RPM", 3, UasDecoder(7), live: false, maxValue: 8000, minValue: 0)),
    "010D": ObdCommand(CommandProperties("010D", "Vehicle Speed", 2, UasDecoder(9), live: false, maxValue: 280, minValue: 0)),
    "010E": ObdCommand(CommandProperties("010E", "Timing Advance", 2, TimingAdvanceDecoder(), live: true, maxValue: 64, minValue: -64)),
    "010F": ObdCommand(CommandProperties("010F", "Intake Air Temp", 2, TemperatureDecoder(), live: true, maxValue: 215, minValue: -40)),
    "0110": ObdCommand(CommandProperties("0110", "Air Flow Rate (MAF)", 3, UasDecoder(39), live: false, maxValue: 100, minValue: 0)),
    "0111": ObdCommand(CommandProperties("0111", "Throttle Position", 2, PercentDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0112": ObdCommand(CommandProperties("0112", "Secondary Air Status", 2, AirStatusDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0113": ObdCommand(CommandProperties("0113", "O2 Sensors Present", 2, O2SensorsDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0114": ObdCommand(CommandProperties("0114", "O2: Bank 1 - Sensor 1 Voltage", 3, SensorVoltageDecoder(), live: true, maxValue: 1.275, minValue: 0)),
    "0115": ObdCommand(CommandProperties("0115", "O2: Bank 1 - Sensor 2 Voltage", 3, SensorVoltageDecoder(), live: true, maxValue: 1.275, minValue: 0)),
    "0116": ObdCommand(CommandProperties("0116", "O2: Bank 1 - Sensor 3 Voltage", 3, SensorVoltageDecoder(), live: true, maxValue: 1.275, minValue: 0)),
    "0117": ObdCommand(CommandProperties("0117", "O2: Bank 1 - Sensor 4 Voltage", 3, SensorVoltageDecoder(), live: true, maxValue: 1.275, minValue: 0)),
    "0118": ObdCommand(CommandProperties("0118", "O2: Bank 2 - Sensor 1 Voltage", 3, SensorVoltageDecoder(), live: true, maxValue: 1.275, minValue: 0)),
    "0119": ObdCommand(CommandProperties("0119", "O2: Bank 2 - Sensor 2 Voltage", 3, SensorVoltageDecoder(), live: true, maxValue: 1.275, minValue: 0)),
    "011A": ObdCommand(CommandProperties("011A", "O2: Bank 2 - Sensor 3 Voltage", 3, SensorVoltageDecoder(), live: true, maxValue: 1.275, minValue: 0)),
    "011B": ObdCommand(CommandProperties("011B", "O2: Bank 2 - Sensor 4 Voltage", 3, SensorVoltageDecoder(), live: true, maxValue: 1.275, minValue: 0)),
    "011C": ObdCommand(CommandProperties("011C", "OBD Standards Compliance", 2, OBDComplianceDecoder(), live: false, maxValue: 100, minValue: 0)),
    "011D": ObdCommand(CommandProperties("011D", "O2 Sensors Present (alternate)", 2, O2SensorsAltDecoder(), live: false, maxValue: 100, minValue: 0)),
    "011E": ObdCommand(CommandProperties("011E", "Auxiliary input status (power take off)", 2, null, live: false, maxValue: 100, minValue: 0)),
    "011F": ObdCommand(CommandProperties("011F", "Engine Run Time", 3, UasDecoder(18), live: false, maxValue: 100, minValue: 0)),
    "0120": ObdCommand(CommandProperties("0120", "Supported PIDs [21-40]", 5, null, live: false, maxValue: 100, minValue: 0)),
    "0121": ObdCommand(CommandProperties("0121", "Distance Traveled with MIL on", 4, UasDecoder(37), live: false, maxValue: 100, minValue: 0)),
    "0122": ObdCommand(CommandProperties("0122", "Fuel Rail Pressure (relative to vacuum)", 3, UasDecoder(25), live: false, maxValue: 100, minValue: 0)),
    "0123": ObdCommand(CommandProperties("0123", "Fuel Rail Pressure (direct inject)", 3, UasDecoder(27), live: false, maxValue: 100, minValue: 0)),
    "0124": ObdCommand(CommandProperties("0124", "02 Sensor 1 WR Lambda Voltage", 5, SensorVoltageBigDecoder(), live: true, maxValue: 8.192, minValue: 0)),
    "0125": ObdCommand(CommandProperties("0125", "02 Sensor 2 WR Lambda Voltage", 5, SensorVoltageBigDecoder(), live: true, maxValue: 8.192, minValue: 0)),
    "0126": ObdCommand(CommandProperties("0126", "02 Sensor 3 WR Lambda Voltage", 5, SensorVoltageBigDecoder(), live: true, maxValue: 8.192, minValue: 0)),
    "0127": ObdCommand(CommandProperties("0127", "02 Sensor 4 WR Lambda Voltage", 5, SensorVoltageBigDecoder(), live: true, maxValue: 8.192, minValue: 0)),
    "0128": ObdCommand(CommandProperties("0128", "02 Sensor 5 WR Lambda Voltage", 5, SensorVoltageBigDecoder(), live: true, maxValue: 8.192, minValue: 0)),
    "0129": ObdCommand(CommandProperties("0129", "02 Sensor 6 WR Lambda Voltage", 5, SensorVoltageBigDecoder(), live: true, maxValue: 8.192, minValue: 0)),
    "012A": ObdCommand(CommandProperties("012A", "02 Sensor 7 WR Lambda Voltage", 5, SensorVoltageBigDecoder(), live: true, maxValue: 8.192, minValue: 0)),
    "012B": ObdCommand(CommandProperties("012B", "02 Sensor 8 WR Lambda Voltage", 5, SensorVoltageBigDecoder(), live: true, maxValue: 8.192, minValue: 0)),
    "012C": ObdCommand(CommandProperties("012C", "Commanded EGR", 2, PercentDecoder(), live: true, maxValue: 100, minValue: 0)),
    "012D": ObdCommand(CommandProperties("012D", "EGR Error", 2, PercentCenteredDecoder(), live: true, maxValue: 100, minValue: 0)),
    "012E": ObdCommand(CommandProperties("012E", "Commanded Evaporative Purge", 2, PercentDecoder(), live: true, maxValue: 100, minValue: 0)),
    "012F": ObdCommand(CommandProperties("012F", "Fuel Tank Level Input", 2, PercentDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0130": ObdCommand(CommandProperties("0130", "Number of warm-ups since codes cleared", 2, UasDecoder(1), live: false, maxValue: 100, minValue: 0)),
    "0131": ObdCommand(CommandProperties("0131", "Distance traveled since codes cleared", 3, UasDecoder(37), live: false, maxValue: 65535, minValue: 0)),
    "0132": ObdCommand(CommandProperties("0132", "Evaporative system vapor pressure", 3, EvapPressureDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0133": ObdCommand(CommandProperties("0133", "Barometric Pressure", 2, PressureDecoder(), live: true, maxValue: 255, minValue: 0)),
    "0134": ObdCommand(CommandProperties("0134", "02 Sensor 1 WR Lambda Current", 2, CurrentCenteredDecoder(), live: true, maxValue: 128, minValue: -128)),
    "0135": ObdCommand(CommandProperties("0135", "02 Sensor 2 WR Lambda Current", 2, CurrentCenteredDecoder(), live: true, maxValue: 128, minValue: -128)),
    "0136": ObdCommand(CommandProperties("0136", "02 Sensor 3 WR Lambda Current", 2, CurrentCenteredDecoder(), live: true, maxValue: 128, minValue: -128)),
    "0137": ObdCommand(CommandProperties("0137", "02 Sensor 4 WR Lambda Current", 2, CurrentCenteredDecoder(), live: true, maxValue: 128, minValue: -128)),
    "0138": ObdCommand(CommandProperties("0138", "02 Sensor 5 WR Lambda Current", 2, CurrentCenteredDecoder(), live: true, maxValue: 128, minValue: -128)),
    "0139": ObdCommand(CommandProperties("0139", "02 Sensor 6 WR Lambda Current", 2, CurrentCenteredDecoder(), live: true, maxValue: 128, minValue: -128)),
    "013A": ObdCommand(CommandProperties("013A", "02 Sensor 7 WR Lambda Current", 2, CurrentCenteredDecoder(), live: true, maxValue: 128, minValue: -128)),
    "013B": ObdCommand(CommandProperties("013B", "02 Sensor 8 WR Lambda Current", 2, CurrentCenteredDecoder(), live: true, maxValue: 128, minValue: -128)),
    "013C": ObdCommand(CommandProperties("013C", "Catalyst Temperature: Bank 1 - Sensor 1", 3, UasDecoder(22), live: false, maxValue: 100, minValue: 0)),
    "013D": ObdCommand(CommandProperties("013D", "Catalyst Temperature: Bank 2 - Sensor 1", 3, UasDecoder(22), live: false, maxValue: 100, minValue: 0)),
    "013E": ObdCommand(CommandProperties("013E", "Catalyst Temperature: Bank 1 - Sensor 2", 3, UasDecoder(22), live: false, maxValue: 100, minValue: 0)),
    "013F": ObdCommand(CommandProperties("013F", "Catalyst Temperature: Bank 1 - Sensor 2", 3, UasDecoder(22), live: false, maxValue: 100, minValue: 0)),
    "0140": ObdCommand(CommandProperties("0140", "Supported PIDs [41-60]", 5, null, live: false, maxValue: 100, minValue: 0)),
    "0141": ObdCommand(CommandProperties("0141", "Monitor status this drive cycle", 5, StatusDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0142": ObdCommand(CommandProperties("0142", "Control module voltage", 3, UasDecoder(11), live: false, maxValue: 100, minValue: 0)),
    "0143": ObdCommand(CommandProperties("0143", "Absolute load value", 3, PercentDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0144": ObdCommand(CommandProperties("0144", "Commanded equivalence ratio", 3, UasDecoder(30), live: false, maxValue: 100, minValue: 0)),
    "0145": ObdCommand(CommandProperties("0145", "Relative throttle position", 2, PercentDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0146": ObdCommand(CommandProperties("0146", "Ambient air temperature", 2, TemperatureDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0147": ObdCommand(CommandProperties("0147", "Absolute throttle position B", 2, PercentDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0148": ObdCommand(CommandProperties("0148", "Absolute throttle position C", 2, PercentDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0149": ObdCommand(CommandProperties("0149", "Absolute throttle position D", 2, PercentDecoder(), live: true, maxValue: 100, minValue: 0)),
    "014A": ObdCommand(CommandProperties("014A", "Absolute throttle position E", 2, PercentDecoder(), live: true, maxValue: 100, minValue: 0)),
    "014B": ObdCommand(CommandProperties("014B", "Absolute throttle position F", 2, PercentDecoder(), live: true, maxValue: 100, minValue: 0)),
    "014C": ObdCommand(CommandProperties("014C", "Commanded throttle actuator", 2, PercentDecoder(), live: true, maxValue: 100, minValue: 0)),
    "014D": ObdCommand(CommandProperties("014D", "Time run with MIL on", 3, UasDecoder(18), live: false, maxValue: 100, minValue: 0)),
    "014E": ObdCommand(CommandProperties("014E", "Time since trouble codes cleared", 3, UasDecoder(18), live: false, maxValue: 100, minValue: 0)),
    "014F": ObdCommand(CommandProperties("014F", "Maximum value for various values", 6, null, live: false, maxValue: 100, minValue: 0)),
    "0150": ObdCommand(CommandProperties("0150", "Maximum value for air flow rate from mass air flow sensor", 4, MaxMafDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0151": ObdCommand(CommandProperties("0151", "Fuel Type", 2, FuelTypeDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0152": ObdCommand(CommandProperties("0152", "Ethanol fuel %", 2, PercentDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0153": ObdCommand(CommandProperties("0153", "Absolute Evap system vapor pressure", 3, EvapPressureAltDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0154": ObdCommand(CommandProperties("0154", "Evap system vapor pressure", 3, EvapPressureAltDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0155": ObdCommand(CommandProperties("0155", "Short term secondary O2 trim - Bank 1", 3, PercentCenteredDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0156": ObdCommand(CommandProperties("0156", "Long term secondary O2 trim - Bank 1", 3, PercentCenteredDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0157": ObdCommand(CommandProperties("0157", "Short term secondary O2 trim - Bank 2", 3, PercentCenteredDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0158": ObdCommand(CommandProperties("0158", "Long term secondary O2 trim - Bank 2", 3, PercentCenteredDecoder(), live: true, maxValue: 100, minValue: 0)),
    "0159": ObdCommand(CommandProperties("0159", "Fuel rail pressure (absolute)", 3, UasDecoder(27), live: false, maxValue: 100, minValue: 0)),
    "015A": ObdCommand(CommandProperties("015A", "Relative accelerator pedal position", 3, PercentDecoder(), live: true, maxValue: 100, minValue: 0)),
    "015B": ObdCommand(CommandProperties("015B", "Hybrid battery pack remaining life", 3, PercentDecoder(), live: false, maxValue: 100, minValue: 0)),
    "015C": ObdCommand(CommandProperties("015C", "Engine oil temperature", 2, TemperatureDecoder(), live: true, maxValue: 215, minValue: -40)),
    "015D": ObdCommand(CommandProperties("015D", "Fuel injection timing", 3, InjectTimingDecoder(), live: true, maxValue: 100, minValue: 0)),
    "015E": ObdCommand(CommandProperties("015E", "Engine fuel rate", 3, FuelRateDecoder(), live: true, maxValue: 100, minValue: 0)),
    "04": ObdCommand(CommandProperties("04", "Clear DTCs and freeze data", 0, null, live: false, maxValue: 100, minValue: 0)),
    "015F": ObdCommand(CommandProperties("015F", "Designed emission requirements", 3, null, live: false, maxValue: 100, minValue: 0)),
    "03": ObdCommand(CommandProperties("03", "Get DTCs", 0, DtcDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0600": ObdCommand(CommandProperties("0600", "Supported MIDs [01-20]", 0, null, live: false, maxValue: 100, minValue: 0)),
    "0601": ObdCommand(CommandProperties("0601", "O2 Sensor Monitor Bank 1 - Sensor 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0602": ObdCommand(CommandProperties("0602", "O2 Sensor Monitor Bank 1 - Sensor 2", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0603": ObdCommand(CommandProperties("0603", "O2 Sensor Monitor Bank 1 - Sensor 3", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0604": ObdCommand(CommandProperties("0604", "O2 Sensor Monitor Bank 1 - Sensor 4", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0605": ObdCommand(CommandProperties("0605", "O2 Sensor Monitor Bank 2 - Sensor 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0606": ObdCommand(CommandProperties("0606", "O2 Sensor Monitor Bank 2 - Sensor 2", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0607": ObdCommand(CommandProperties("0607", "O2 Sensor Monitor Bank 2 - Sensor 3", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0608": ObdCommand(CommandProperties("0608", "O2 Sensor Monitor Bank 2 - Sensor 4", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0609": ObdCommand(CommandProperties("0609", "O2 Sensor Monitor Bank 3 - Sensor 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "060A": ObdCommand(CommandProperties("060A", "O2 Sensor Monitor Bank 3 - Sensor 2", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "060B": ObdCommand(CommandProperties("060B", "O2 Sensor Monitor Bank 3 - Sensor 3", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "060C": ObdCommand(CommandProperties("060C", "O2 Sensor Monitor Bank 3 - Sensor 4", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "060D": ObdCommand(CommandProperties("060D", "O2 Sensor Monitor Bank 4 - Sensor 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "060E": ObdCommand(CommandProperties("060E", "O2 Sensor Monitor Bank 4 - Sensor 2", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "060F": ObdCommand(CommandProperties("060F", "O2 Sensor Monitor Bank 4 - Sensor 3", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0610": ObdCommand(CommandProperties("0610", "O2 Sensor Monitor Bank 4 - Sensor 4", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0620": ObdCommand(CommandProperties("0620", "Supported MIDs [21-40]", 0, null, live: false, maxValue: 100, minValue: 0)),
    "0621": ObdCommand(CommandProperties("0621", "Catalyst Monitor Bank 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0622": ObdCommand(CommandProperties("0622", "Catalyst Monitor Bank 2", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0623": ObdCommand(CommandProperties("0623", "Catalyst Monitor Bank 3", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0624": ObdCommand(CommandProperties("0624", "Catalyst Monitor Bank 4", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0631": ObdCommand(CommandProperties("0631", "EGR Monitor Bank 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0632": ObdCommand(CommandProperties("0632", "EGR Monitor Bank 2", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0633": ObdCommand(CommandProperties("0633", "EGR Monitor Bank 3", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0634": ObdCommand(CommandProperties("0634", "EGR Monitor Bank 4", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0635": ObdCommand(CommandProperties("0635", "VVT Monitor Bank 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0636": ObdCommand(CommandProperties("0636", "VVT Monitor Bank 2", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0637": ObdCommand(CommandProperties("0637", "VVT Monitor Bank 3", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0638": ObdCommand(CommandProperties("0638", "VVT Monitor Bank 4", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0639": ObdCommand(CommandProperties("0639", "EVAP Monitor (Cap Off / 0.150\")", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "063A": ObdCommand(CommandProperties("063A", "EVAP Monitor (0.090\")", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "063B": ObdCommand(CommandProperties("063B", "EVAP Monitor (0.040\")", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "063C": ObdCommand(CommandProperties("063C", "EVAP Monitor (0.020\")", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "063D": ObdCommand(CommandProperties("063D", "Purge Flow Monitor", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0640": ObdCommand(CommandProperties("0640", "Supported MIDs [41-60]", 0, null, live: false, maxValue: 100, minValue: 0)),
    "0641": ObdCommand(CommandProperties("0641", "O2 Sensor Heater Monitor Bank 1 - Sensor 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0642": ObdCommand(CommandProperties("0642", "O2 Sensor Heater Monitor Bank 1 - Sensor 2", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0643": ObdCommand(CommandProperties("0643", "O2 Sensor Heater Monitor Bank 1 - Sensor 3", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0644": ObdCommand(CommandProperties("0644", "O2 Sensor Heater Monitor Bank 1 - Sensor 4", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0645": ObdCommand(CommandProperties("0645", "O2 Sensor Heater Monitor Bank 2 - Sensor 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0646": ObdCommand(CommandProperties("0646", "O2 Sensor Heater Monitor Bank 2 - Sensor 2", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0647": ObdCommand(CommandProperties("0647", "O2 Sensor Heater Monitor Bank 2 - Sensor 3", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0648": ObdCommand(CommandProperties("0648", "O2 Sensor Heater Monitor Bank 2 - Sensor 4", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0649": ObdCommand(CommandProperties("0649", "O2 Sensor Heater Monitor Bank 3 - Sensor 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "064A": ObdCommand(CommandProperties("064A", "O2 Sensor Heater Monitor Bank 3 - Sensor 2", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "064B": ObdCommand(CommandProperties("064B", "O2 Sensor Heater Monitor Bank 3 - Sensor 3", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "064C": ObdCommand(CommandProperties("064C", "O2 Sensor Heater Monitor Bank 3 - Sensor 4", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "064D": ObdCommand(CommandProperties("064D", "O2 Sensor Heater Monitor Bank 4 - Sensor 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "064E": ObdCommand(CommandProperties("064E", "O2 Sensor Heater Monitor Bank 4 - Sensor 2", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "064F": ObdCommand(CommandProperties("064F", "O2 Sensor Heater Monitor Bank 4 - Sensor 3", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0650": ObdCommand(CommandProperties("0650", "O2 Sensor Heater Monitor Bank 4 - Sensor 4", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0660": ObdCommand(CommandProperties("0660", "Supported MIDs [61-80]", 0, null, live: false, maxValue: 100, minValue: 0)),
    "0661": ObdCommand(CommandProperties("0661", "Heated Catalyst Monitor Bank 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0662": ObdCommand(CommandProperties("0662", "Heated Catalyst Monitor Bank 2", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0663": ObdCommand(CommandProperties("0663", "Heated Catalyst Monitor Bank 3", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0664": ObdCommand(CommandProperties("0664", "Heated Catalyst Monitor Bank 4", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0671": ObdCommand(CommandProperties("0671", "Secondary Air Monitor 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0672": ObdCommand(CommandProperties("0672", "Secondary Air Monitor 2", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0673": ObdCommand(CommandProperties("0673", "Secondary Air Monitor 3", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0674": ObdCommand(CommandProperties("0674", "Secondary Air Monitor 4", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0680": ObdCommand(CommandProperties("0680", "Supported MIDs [81-A0]", 0, null, live: false, maxValue: 100, minValue: 0)),
    "0681": ObdCommand(CommandProperties("0681", "Fuel System Monitor Bank 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0682": ObdCommand(CommandProperties("0682", "Fuel System Monitor Bank 2", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0683": ObdCommand(CommandProperties("0683", "Fuel System Monitor Bank 3", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0684": ObdCommand(CommandProperties("0684", "Fuel System Monitor Bank 4", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0685": ObdCommand(CommandProperties("0685", "Boost Pressure Control Monitor Bank 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0686": ObdCommand(CommandProperties("0686", "Boost Pressure Control Monitor Bank 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0690": ObdCommand(CommandProperties("0690", "NOx Absorber Monitor Bank 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0691": ObdCommand(CommandProperties("0691", "NOx Absorber Monitor Bank 2", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0698": ObdCommand(CommandProperties("0698", "NOx Catalyst Monitor Bank 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0699": ObdCommand(CommandProperties("0699", "NOx Catalyst Monitor Bank 2", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "06A0": ObdCommand(CommandProperties("06A0", "Supported MIDs [A1-C0]", 0, null, live: false, maxValue: 100, minValue: 0)),
    "06A1": ObdCommand(CommandProperties("06A1", "Misfire Monitor General Data", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "06A2": ObdCommand(CommandProperties("06A2", "Misfire Cylinder 1 Data", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "06A3": ObdCommand(CommandProperties("06A3", "Misfire Cylinder 2 Data", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "06A4": ObdCommand(CommandProperties("06A4", "Misfire Cylinder 3 Data", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "06A5": ObdCommand(CommandProperties("06A5", "Misfire Cylinder 4 Data", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "06A6": ObdCommand(CommandProperties("06A6", "Misfire Cylinder 5 Data", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "06A7": ObdCommand(CommandProperties("06A7", "Misfire Cylinder 6 Data", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "06A8": ObdCommand(CommandProperties("06A8", "Misfire Cylinder 7 Data", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "06A9": ObdCommand(CommandProperties("06A9", "Misfire Cylinder 8 Data", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "06AA": ObdCommand(CommandProperties("06AA", "Misfire Cylinder 9 Data", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "06AB": ObdCommand(CommandProperties("06AB", "Misfire Cylinder 10 Data", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "06AC": ObdCommand(CommandProperties("06AC", "Misfire Cylinder 11 Data", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "06AD": ObdCommand(CommandProperties("06AD", "Misfire Cylinder 12 Data", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "06B0": ObdCommand(CommandProperties("06B0", "PM Filter Monitor Bank 1", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "06B1": ObdCommand(CommandProperties("06B1", "PM Filter Monitor Bank 2", 0, MonitorDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0900": ObdCommand(CommandProperties("0900", "Supported PIDs [01-20]", 7, null, live: false, maxValue: 100, minValue: 0)),
    "0901": ObdCommand(CommandProperties("0901", "VIN Message Count", 3, null, live: false, maxValue: 100, minValue: 0)),
    "0902": ObdCommand(CommandProperties("0902", "Vehicle Identification Number", 22, StringDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0903": ObdCommand(CommandProperties("0903", "Calibration ID message count for PID 04", 3, null, live: false, maxValue: 100, minValue: 0)),
    "0904": ObdCommand(CommandProperties("0904", "Calibration ID", 18, StringDecoder(), live: false, maxValue: 100, minValue: 0)),
    "0905": ObdCommand(CommandProperties("0905", "CVN Message Count for PID 06", 3, null, live: false, maxValue: 100, minValue: 0)),
    "0906": ObdCommand(CommandProperties("0906", "Calibration Verification Numbers", 10, null, live: false, maxValue: 100, minValue: 0)),
    "ATSP0": ObdCommand(CommandProperties("ATSP0", "Auto protocol", 0, null, live: false, maxValue: 100, minValue: 0)),
    "ATSP6": ObdCommand(CommandProperties("ATSP6", "Auto protocol", 0, null, live: false, maxValue: 100, minValue: 0)),
    "221154": ObdCommand(CommandProperties("221154", "Engine Oil Temp", 3, TemperatureDecoder(), live: true, maxValue: 215, minValue: -40)),
    "221940": ObdCommand(CommandProperties("221940", "Transmission Fluid Temp", 3, TemperatureDecoder(), live: true, maxValue: 215, minValue: -40)),
    "221470": ObdCommand(CommandProperties("221470", "Engine Oil Pressure", 3, GMEngineOilPressureDecoder(), live: true, maxValue: 100, minValue: 0)),
    "221144": ObdCommand(CommandProperties("221144", "Air Conditioner High Pressure", 3, GMACPressureDecoder(), live: true, maxValue: 100, minValue: 0)),
  };

  static const List<String> pidGetterCommands = [
    "0100",
    "0120",
    "0140",
    "0600",
    "0620",
    "0640",
    "0660",
    "0680",
    "06A0",
    "0900",
  ];
}
