sonar.organization=jamesmittlerii
sonar.projectKey=jamesmittlerii_SwiftOBD2
sonar.host.url=https://sonarcloud.io

sonar.sources=flutterobd2/lib,kotlinobd2/src/main,swiftobd2/Sources
sonar.tests=flutterobd2/test,kotlinobd2/src/test,swiftobd2/Tests
sonar.dart.lcov.reportPaths=flutterobd2/coverage/lcov.info
sonar.coverage.jacoco.xmlReportPaths=kotlinobd2/build/reports/jacoco/test/jacocoTestReport.xml
sonar.coverageReportPaths=coverage/sonar-generic-coverage.xml
sonar.exclusions=**/*Tests.swift
sonar.coverage.exclusions=swiftobd2/Sources/SwiftOBD2/Communication/BLE/**,swiftobd2/Sources/SwiftOBD2/Communication/wifiManager.swift
sonar.sourceEncoding=UTF-8

