name: flutter_obd2
description: A complete port of SwiftOBD2, providing an easy-to-use interface to communicate with ELM327 OBD2 adapters over BLE and Wi-Fi.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^2.2.1
  collection: ^1.18.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
