name: flutter_obd2
description: A complete port of SwiftOBD2, providing an easy-to-use interface to communicate with ELM327 OBD2 adapters over BLE and Wi-Fi.
version: 0.1.6
homepage: https://github.com/jamesmittlerii/SwiftOBD2/tree/main/flutterobd2
repository: https://github.com/jamesmittlerii/SwiftOBD2
issue_tracker: https://github.com/jamesmittlerii/SwiftOBD2/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^2.2.1
  collection: ^1.18.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - lib/src/data/codes.json
    - lib/src/data/commands.enriched.json
    - lib/src/data/command_aliases.json
