name: Publish to Pub.dev

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*' # Matches 1.0.0, 2.1.4, etc.
  workflow_dispatch:          # Enables the manual run button in the GitHub UI

jobs:
  # Call the official reusable Dart publishing workflow
  publish:
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      # Tell it where your Flutter package lives relative to the repo root
      working-directory: flutterobd2
